# TCL File Generated by Component Editor 13.1
# Thu Dec 22 16:13:08 UTC 2016
# DO NOT MODIFY


# 
# Can_hw_controller "Can_hw_controller" v1.0
#  2016.12.22.16:13:08
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module Can_hw_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME Can_hw_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Can_hw_controller
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Can_hw_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL can_vhdl_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file can_vhdl_acf.vhdl VHDL PATH Can/can_vhdl_acf.vhdl
add_fileset_file can_vhdl_bsp.vhdl VHDL PATH Can/can_vhdl_bsp.vhdl
add_fileset_file "can_vhdl_btl .vhdl" VHDL PATH "Can/can_vhdl_btl .vhdl"
add_fileset_file can_vhdl_crc.vhdl VHDL PATH Can/can_vhdl_crc.vhdl
add_fileset_file can_vhdl_fifo.vhdl VHDL PATH Can/can_vhdl_fifo.vhdl
add_fileset_file can_vhdl_ibo.vhdl VHDL PATH Can/can_vhdl_ibo.vhdl
add_fileset_file can_vhdl_register.vhdl VHDL PATH Can/can_vhdl_register.vhdl
add_fileset_file can_vhdl_register_asyn.vhdl VHDL PATH Can/can_vhdl_register_asyn.vhdl
add_fileset_file can_vhdl_register_asyn_syn.vhdl VHDL PATH Can/can_vhdl_register_asyn_syn.vhdl
add_fileset_file can_vhdl_registers.vhdl VHDL PATH Can/can_vhdl_registers.vhdl
add_fileset_file can_vhdl_top.vhdl VHDL PATH Can/can_vhdl_top.vhdl TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL can_vhdl_top
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file can_vhdl_acf.vhdl VHDL PATH Can/can_vhdl_acf.vhdl
add_fileset_file can_vhdl_bsp.vhdl VHDL PATH Can/can_vhdl_bsp.vhdl
add_fileset_file "can_vhdl_btl .vhdl" VHDL PATH "Can/can_vhdl_btl .vhdl"
add_fileset_file can_vhdl_crc.vhdl VHDL PATH Can/can_vhdl_crc.vhdl
add_fileset_file can_vhdl_fifo.vhdl VHDL PATH Can/can_vhdl_fifo.vhdl
add_fileset_file can_vhdl_ibo.vhdl VHDL PATH Can/can_vhdl_ibo.vhdl
add_fileset_file can_vhdl_register.vhdl VHDL PATH Can/can_vhdl_register.vhdl
add_fileset_file can_vhdl_register_asyn.vhdl VHDL PATH Can/can_vhdl_register_asyn.vhdl
add_fileset_file can_vhdl_register_asyn_syn.vhdl VHDL PATH Can/can_vhdl_register_asyn_syn.vhdl
add_fileset_file can_vhdl_registers.vhdl VHDL PATH Can/can_vhdl_registers.vhdl
add_fileset_file can_vhdl_top.vhdl VHDL PATH Can/can_vhdl_top.vhdl


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 av_dat_i writedata Input 8
add_interface_port avalon_slave_0 av_we_i write Input 1
add_interface_port avalon_slave_0 av_adr_i address Input 8
add_interface_port avalon_slave_0 av_cs_i chipselect Input 1
add_interface_port avalon_slave_0 av_dat_o readdata Output 8
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink av_rst_i reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end rx_i export Input 1
add_interface_port conduit_end tx_o export Output 1
add_interface_port conduit_end bus_off_on export Output 1
add_interface_port conduit_end irq_on export Output 1
add_interface_port conduit_end clkout_o export Output 1

